import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <p>selam dükkanım</p>
        <p>selam dükkanım</p>
        <p>selam dükkanım</p>
        <p>selam dükkanım</p>
        <p>selam dükkanım</p>
        <p>selam dükkanım</p>
        <p>selam dükkanım</p>
        <p>selam dükkanım</p>
        <p>selam dükkanım</p>
        <p>selam dükkanım</p>
        <p>selam dükkanım</p>
        <p>selam dükkanım</p>
        <p>selam dükkanım</p>
        <p>selam dükkanım</p>
        <p>selam dükkanım</p>
        <p>selam dükkanım</p>
      </main>
    </div>
  )
}
