import Head from 'next/head'
import Classes from '../styles/index.module.scss'
import {AiOutlineArrowRight} from 'react-icons/ai'
import { useRouter } from 'next/router';

export default function Home() {
  const router = useRouter();
  return (
    <div className={Classes.homeMain}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className={Classes.cards}> 
        <div onClick={()=>router.push("Giris")}><p>Giriş yap alışverişe başla!</p></div>
        <div><p>Fırsat ürünleri</p></div>
        <a href='https://berk-portfolio.vercel.app/' target="_blank" rel='noreferrer'><p>Portfolyo</p></a>
        <div>
          <p>Bültene abone ol fırsatları kaçırma!</p>
          <section>
            <input type="email"/>
            <button><AiOutlineArrowRight size={20}/></button>
          </section>
          </div>
        </section>
      </main>
    </div>
  )
}
